//! E2E art scenes: tribute sprites, layer backdrop, animated FIGBY banner.
//!
//! The scenes live in `assets/e2e-art/*.figmap` and are generated by
//! `scripts/gen-e2e-art.py` (all art is original tribute work, no ROM copies).
//! These tests pin the structural contract the TUI depends on: figmap loads,
//! layer counts/names, timeline frame/layer-count agreement, light keyframe
//! shape, and banner glyph content rendered by the real `fonts/big` font.

use std::path::PathBuf;

fn art_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .join("assets")
        .join("e2e-art")
}

fn load(name: &str) -> figby::figmap::FigmapFile {
    let path = art_dir().join(name);
    figby::figmap::load_figmap(&path).unwrap_or_else(|e| panic!("{name} must load: {e}"))
}

fn painted(buf: &figby::tui::canvas::CanvasBuffer) -> usize {
    (0..buf.height())
        .flat_map(|y| (0..buf.width()).map(move |x| (x, y)))
        .filter(|&(x, y)| buf.get(x, y).is_some_and(|c| c.ch != ' '))
        .count()
}

fn gold(buf: &figby::tui::canvas::CanvasBuffer) -> usize {
    (0..buf.height())
        .flat_map(|y| (0..buf.width()).map(move |x| (x, y)))
        .filter(|&(x, y)| {
            buf.get(x, y).is_some_and(|c| {
                c.ch != ' ' && c.fg == Some(ratatui::style::Color::Rgb(255, 215, 0))
            })
        })
        .count()
}

#[test]
fn e2e_art_sprites_load_with_hero_layer() {
    for name in [
        "sprite-plumber-tribute.figmap",
        "sprite-quest-tribute.figmap",
        "sprite-invader-tribute.figmap",
    ] {
        let fig = load(name);
        assert_eq!((fig.width, fig.height), (40, 20), "{name} dims");
        assert_eq!(fig.layers.len(), 2, "{name} layer count");
        assert_eq!(fig.layers[0].name, "Background");
        assert_eq!(fig.layers[1].name, "Hero");
        assert_eq!(fig.active_layer, 1);
        // Hero layer actually paints something (the tribute sprite).
        let hero = painted(&fig.layers[1].buffer);
        assert!(hero >= 20, "{name} hero looks empty ({hero} cells)");
        // Background flair layer paints too (gradient, not blank).
        let bg = painted(&fig.layers[0].buffer);
        assert!(bg > 100, "{name} background looks empty");
    }
}

#[test]
fn e2e_art_castle_has_three_named_layers() {
    let fig = load("layers-castle-tribute.figmap");
    assert_eq!((fig.width, fig.height), (64, 20));
    let names: Vec<_> = fig.layers.iter().map(|l| l.name.as_str()).collect();
    assert_eq!(names, ["Sky", "Castle", "Hero"]);
    assert_eq!(fig.active_layer, 2);
    // Castle keep mid-layer paints bricks; hero top-layer paints the sprite.
    for (idx, min) in [(1, 100), (2, 20)] {
        let n = painted(&fig.layers[idx].buffer);
        assert!(n >= min, "layer {idx} looks empty ({n} cells)");
    }
}

#[test]
fn e2e_art_banner_is_animation_with_lights() {
    let fig = load("banner-figby-finale.figmap");
    assert_eq!(fig.kind, figby::figmap::FigmapKind::Animation);
    assert_eq!((fig.width, fig.height), (64, 24));
    let tl = fig.timeline.as_ref().expect("banner has a timeline");
    assert_eq!(tl.frames.len(), 6);
    assert!(tl.loop_enabled);
    assert_eq!(tl.fps, 8);
    // Each frame carries one committed buffer matching the document size.
    for (i, f) in tl.frames.iter().enumerate() {
        assert_eq!(f.document_state.len(), 1, "frame {i} layer count");
        let buf = &f.document_state[0];
        assert_eq!((buf.width(), buf.height()), (64, 24), "frame {i} dims");
        // Gold banner glyphs survive in every frame.
        let g = gold(buf);
        assert!(g > 30, "frame {i} lost its banner ({g} gold cells)");
    }
    // Light rig: ambient base + one animated point light sweeping the banner.
    assert_eq!(fig.lights.len(), 2);
    assert_eq!(tl.light_keyframes.len(), 2);
    assert_eq!(tl.light_keyframes[0].light_index, 1);
    assert!(tl.light_keyframes[0].time < tl.light_keyframes[1].time);
}

#[test]
fn e2e_art_banner_into_runtime_composites() {
    let fig = load("banner-figby-finale.figmap");
    let (layers, timeline, lights, _palette) = figby::figmap::into_runtime(fig);
    assert!(!layers.layers.is_empty());
    assert_eq!(lights.len(), 2);
    let tl = timeline.expect("banner timeline survives into_runtime");
    assert_eq!(tl.frames.len(), 6);
    // The runtime composite path used by --play never panics on these frames.
    let composite = layers.composite();
    assert_eq!((composite.width(), composite.height()), (64, 24));
}
